
[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[9;6u"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[59;5u"
key = "Semicolon"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;6u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;6u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[colors.bright]
black = "#686868"
blue = "#00afff"      # Vivid blue, also high contrast
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#268bd2"      # Solarized blue, good contrast
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#0A0E14"
foreground = "#B3B1AD"


[colors.selection]
text = "#000000"
background = "#afd7ff"  # Light blue background for selection

[font]
size = 12

[font.bold]
family = "mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "mononoki Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.92

[window.padding]
x = 5
y = 5

[keyboard]
